### ISSUE TITLE
Could not  add custom keyboard shortcut and display the website scrennshot

### ISSUE THREAD

**Issue by xyzmst** [deweyapp/dewey#143] opened 2015-11-23 06:53 UTC
Could not  add custom keyboard shortcut and display the website screenshot,
it can not find dewey in the list from add keyboard shortcuts ,the screenshot is loadding can not display.

**Comment by outcoldman** [comment] 2016-03-10 06:01
Duplicate of #145

I have deployed version 4.0.0 which is basically one big change - using our own screenshot generating server.

If you want to help:

As usual we will appreciate if you will contribute to code.
Please consider donation https://github.com/deweyapp/dewey#donate - that will help us to switch to more powerful server.
If you like - please share http://deweyapp.io to your friends and followers.

If you want to be more specific of issue with "custom keyboard shortcut" -  please open new ticket and be more specific what is desired behavior.

**Closed by outcoldman** 2016-03-10 06:01 UTC
